import { useState } from "react";
import { useNavigate } from "react-router-dom";
import AppShell from "../components/AppShell.jsx";
import { upsertPatient } from "../utils/localStorage.js";

const initialForm = {
  name: "",
  age: "",
  gender: "Male",
  mobile: "",
  company: "",
  address: "",
  photo: "",
  fatherName: "",
  occupation: ""
};

export default function PatientRegistration() {
  const [form, setForm] = useState(initialForm);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const navigate = useNavigate();

  function updateField(field, value) {
    setForm((current) => ({ ...current, [field]: value }));
  }

  function handlePhoto(file) {
    if (!file) return;
    const reader = new FileReader();
    reader.onload = () => updateField("photo", reader.result);
    reader.readAsDataURL(file);
  }

  async function handleSubmit(event) {
    event.preventDefault();
    setLoading(true);
    setError("");
    try {
      const createdPatient = await upsertPatient(form);
      if (createdPatient && createdPatient.patientId) {
        navigate(`/patients/${createdPatient.patientId}`);
      } else {
        throw new Error("Invalid response received from server");
      }
    } catch (err) {
      console.error("Failed to register patient:", err);
      setError(err.response?.data?.message || "Failed to create patient record. Please check your inputs.");
    } finally {
      setLoading(false);
    }
  }

  return (
    <AppShell>
      <form onSubmit={handleSubmit} className="mx-auto max-w-5xl rounded-lg border border-line bg-white p-8 shadow-soft">
        <div className="mb-8 flex items-start justify-between">
          <div>
            <h1 className="text-2xl font-semibold">Patient Registration</h1>
            <p className="mt-2 text-muted">Generated Patient ID: <span className="font-medium text-brand">Auto-generated by server</span></p>
          </div>
          <button className="button-primary flex items-center gap-2" type="submit" disabled={loading}>
            {loading && (
              <svg className="animate-spin h-4 w-4 text-white" fill="none" viewBox="0 0 24 24">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
              </svg>
            )}
            {loading ? "Saving..." : "Save Patient"}
          </button>
        </div>

        {error && (
          <div className="mb-6 rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-600 font-semibold">
            {error}
          </div>
        )}

        <div className="grid grid-cols-2 gap-5">
          <Field label="Full Name" value={form.name} onChange={(value) => updateField("name", value)} required />
          <Field label="Age" value={form.age} onChange={(value) => updateField("age", value)} required />
          <div>
            <label className="field-label">Gender</label>
            <select className="input" value={form.gender} onChange={(event) => updateField("gender", event.target.value)}>
              <option>Male</option>
              <option>Female</option>
              <option>Other</option>
            </select>
          </div>
          <Field label="Mobile Number" value={form.mobile} onChange={(value) => updateField("mobile", value)} />
          <Field label="Company Name" value={form.company} onChange={(value) => updateField("company", value)} />
          <Field label="Father's Name" value={form.fatherName} onChange={(value) => updateField("fatherName", value)} />
          <Field label="Designation / Occupation" value={form.occupation} onChange={(value) => updateField("occupation", value)} />
          <div>
            <label className="field-label">Photo Upload</label>
            <input className="input file:mr-4 file:border-0 file:bg-slate-100 file:px-3 file:py-1 file:text-sm" type="file" accept="image/*" onChange={(event) => handlePhoto(event.target.files[0])} />
          </div>
          <div className="col-span-2">
            <label className="field-label" htmlFor="address">Address</label>
            <textarea id="address" className="input min-h-28" value={form.address} onChange={(event) => updateField("address", event.target.value)} />
          </div>
        </div>
      </form>
    </AppShell>
  );
}

function Field({ label, value, onChange, required }) {
  const id = label.toLowerCase().replaceAll(" ", "-");

  return (
    <div>
      <label className="field-label" htmlFor={id}>{label}</label>
      <input id={id} className="input" value={value} required={required} onChange={(event) => onChange(event.target.value)} />
    </div>
  );
}
